#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Tree-reconstruction experiment B — real scraped HTML tables (MultiHiertt).

Unlike HiTab, MultiHiertt hands us tables as raw HTML (`rowspan`/`colspan`,
including occasionally malformed markup) with no pre-built header tree — the
genuinely raw case `scripts/tree_reconstruct_hitab.py` only simulates. This
script parses each table with `rag_agent.reconstruct.parse_html_table`
(which deliberately discards the rowspan/colspan span info after using it
once, to produce the same "blank-after-first" grid a plain HTML->text scrape
would give), guesses the header/data row boundary, reconstructs row/column
header paths, and validates them the only way possible here: MultiHiertt's
own `table_description` field is a natural-language sentence PER DATA CELL
generated by the paper's preprocessing script (keyed `"{table_idx}-{row}-
{col}"` in the table's full grid coordinates — confirmed to line up exactly
with this module's grid indices). A reconstructed header path is scored by
what fraction of its segments appear as substrings of that cell's
description sentence — a proxy, not exact match (no gold tree exists here),
but the MIT-licensed `bevaya/MultiHiertt` repackaging on the Hub makes this
directly runnable with no manual download.

Run: PYTHONPATH=. python scripts/tree_reconstruct_multihiertt.py --max-tables 300
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from rag_agent.reconstruct import guess_n_header_rows, parse_html_table, reconstruct_col_paths, reconstruct_row_paths

_TOK = re.compile(r"[a-z0-9]+")


def size_bucket(n_rows: int, n_cols: int) -> str:
    d = max(n_rows, n_cols)
    if d <= 10:
        return "<=10x10"
    if d <= 20:
        return "10-20"
    return ">20"


def complexity_bucket(nhr: int, has_rowspan: bool) -> str:
    """Complexity independent of raw size: header hierarchy DEPTH (how many
    header rows the table needed) plus whether it uses rowspan at all (a
    structural-complexity signal orthogonal to nhr, since a rowspan can also
    appear within the row-header block)."""
    if nhr >= 4:
        depth = "deep(nhr>=4)"
    elif nhr >= 2:
        depth = "medium(nhr2-3)"
    else:
        depth = "shallow(nhr=1)"
    return f"{depth}{'+rowspan' if has_rowspan else ''}"


def _tokens(s: str):
    return set(_TOK.findall(s.lower()))


def segment_coverage(path, description: str) -> float:
    """Fraction of a header path's segments whose content words all appear
    in the description sentence."""
    if not path:
        return None
    desc_toks = _tokens(description)
    hits = 0
    for seg in path:
        seg_toks = _tokens(seg)
        if not seg_toks:
            continue
        if seg_toks <= desc_toks:
            hits += 1
    return hits / len(path)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hf-dataset", default="bevaya/MultiHiertt")
    ap.add_argument("--split", default="train")
    ap.add_argument("--max-tables", type=int, default=0, help="0 = no cap (all docs)")
    ap.add_argument("--out", default="results/tree_reconstruct_multihiertt.json")
    args = ap.parse_args()

    from datasets import load_dataset
    from collections import defaultdict
    ds = load_dataset(args.hf_dataset, split=args.split)
    docs = ds.to_list()  # `for row in ds` is >100x slower on this dataset

    n_tables = n_parsed = n_rowspan_tables = 0
    bucket_stats = defaultdict(lambda: {"n_tables": 0, "col_coverage": [], "row_coverage": [],
                                         "col_all_hit": 0, "row_all_hit": 0})
    complexity_stats = defaultdict(lambda: {"n_tables": 0, "col_coverage": [], "row_coverage": [],
                                             "col_all_hit": 0, "row_all_hit": 0})
    examples = []

    for doc in docs:
        if args.max_tables and n_tables >= args.max_tables:
            break
        try:
            descriptions = json.loads(doc["table_description"])
        except (json.JSONDecodeError, TypeError):
            descriptions = {}

        for t_idx, html in enumerate(doc["tables"]):
            if args.max_tables and n_tables >= args.max_tables:
                break
            n_tables += 1
            if "rowspan" in html:
                n_rowspan_tables += 1
            grid = parse_html_table(html)
            if len(grid) < 3 or len(grid[0]) < 2:
                continue
            n_parsed += 1

            nhr = guess_n_header_rows(grid, n_header_cols=1)
            nhr = max(1, min(nhr, len(grid) - 1))
            rec_cols = reconstruct_col_paths(grid, nhr, n_header_cols=1)
            rec_rows = reconstruct_row_paths(grid, nhr, n_header_cols=1)

            b = size_bucket(len(grid), len(grid[0]))
            s = bucket_stats[b]
            s["n_tables"] += 1
            cx = complexity_stats[complexity_bucket(nhr, "rowspan" in html)]
            cx["n_tables"] += 1

            for r in range(nhr, len(grid)):
                for c in range(1, len(grid[0])):
                    key = f"{t_idx}-{r}-{c}"
                    desc = descriptions.get(key)
                    if not desc:
                        continue
                    cp = rec_cols[c - 1] if (c - 1) < len(rec_cols) else []
                    rp = rec_rows[r - nhr] if (r - nhr) < len(rec_rows) else []
                    cc = segment_coverage(cp, desc)
                    rc = segment_coverage(rp, desc)
                    for target in (s, cx):
                        if cc is not None:
                            target["col_coverage"].append(cc)
                            target["col_all_hit"] += int(cc >= 0.999)
                        if rc is not None:
                            target["row_coverage"].append(rc)
                            target["row_all_hit"] += int(rc >= 0.999)

                    if len(examples) < 5 and cc is not None and rc is not None:
                        examples.append({
                            "uid": doc["uid"], "table_idx": t_idx, "cell": [r, c],
                            "reconstructed_row_path": rp, "reconstructed_col_path": cp,
                            "description": desc,
                        })

    avg = lambda xs: round(sum(xs) / len(xs), 4) if xs else None
    by_bucket = {}
    all_col_coverage, all_row_coverage = [], []
    all_col_hit = all_row_hit = 0
    for b, s in bucket_stats.items():
        all_col_coverage += s["col_coverage"]; all_row_coverage += s["row_coverage"]
        all_col_hit += s["col_all_hit"]; all_row_hit += s["row_all_hit"]
        by_bucket[b] = {
            "n_tables": s["n_tables"],
            "n_cells_scored": len(s["col_coverage"]),
            "col_path_avg_segment_coverage": avg(s["col_coverage"]),
            "row_path_avg_segment_coverage": avg(s["row_coverage"]),
            "col_path_all_segments_found_rate": round(s["col_all_hit"] / len(s["col_coverage"]), 4) if s["col_coverage"] else None,
            "row_path_all_segments_found_rate": round(s["row_all_hit"] / len(s["row_coverage"]), 4) if s["row_coverage"] else None,
        }

    by_complexity = {}
    for cxk, cx in complexity_stats.items():
        by_complexity[cxk] = {
            "n_tables": cx["n_tables"],
            "n_cells_scored": len(cx["col_coverage"]),
            "col_path_avg_segment_coverage": avg(cx["col_coverage"]),
            "row_path_avg_segment_coverage": avg(cx["row_coverage"]),
            "col_path_all_segments_found_rate": round(cx["col_all_hit"] / len(cx["col_coverage"]), 4) if cx["col_coverage"] else None,
            "row_path_all_segments_found_rate": round(cx["row_all_hit"] / len(cx["row_coverage"]), 4) if cx["row_coverage"] else None,
        }

    out = {
        "population": {"name": "multihiertt_html_tables", "hf_dataset": args.hf_dataset,
                        "split": args.split, "n_tables_seen": n_tables,
                        "n_tables_parsed": n_parsed, "n_tables_with_rowspan": n_rowspan_tables},
        "validation_method": "segment_coverage against table_description "
                              "(proxy — no gold tree exists for this dataset)",
        "n_cells_scored": len(all_col_coverage),
        "col_path_avg_segment_coverage": avg(all_col_coverage),
        "row_path_avg_segment_coverage": avg(all_row_coverage),
        "col_path_all_segments_found_rate": round(all_col_hit / len(all_col_coverage), 4) if all_col_coverage else None,
        "row_path_all_segments_found_rate": round(all_row_hit / len(all_row_coverage), 4) if all_row_coverage else None,
        "by_size_bucket": by_bucket,
        "by_complexity": by_complexity,
        "examples": examples,
    }
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as fh:
        json.dump(out, fh, indent=2)

    print(f"tables seen/parsed  : {n_tables}/{n_parsed}  (rowspan tables: {n_rowspan_tables})")
    print(f"cells scored        : {out['n_cells_scored']}")
    print(f"col_path avg coverage        : {out['col_path_avg_segment_coverage']}  "
          f"(all-segments-found: {out['col_path_all_segments_found_rate']})")
    print(f"row_path avg coverage        : {out['row_path_avg_segment_coverage']}  "
          f"(all-segments-found: {out['row_path_all_segments_found_rate']})")
    print(f"\nby size bucket (max(rows,cols)):")
    for b in ("<=10x10", "10-20", ">20"):
        if b in by_bucket:
            v = by_bucket[b]
            print(f"  {b:<10} n_tables={v['n_tables']:<5} n_cells={v['n_cells_scored']:<6} "
                  f"col_cov={v['col_path_avg_segment_coverage']}  row_cov={v['row_path_avg_segment_coverage']}")
    print(f"\nby complexity (header depth nhr, +rowspan present):")
    for cxk in sorted(by_complexity):
        v = by_complexity[cxk]
        print(f"  {cxk:<24} n_tables={v['n_tables']:<5} n_cells={v['n_cells_scored']:<6} "
              f"col_cov={v['col_path_avg_segment_coverage']}  row_cov={v['row_path_avg_segment_coverage']}")
    print(f"\nwrote -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
