"""Sandboxed pandas expression evaluator.

Accepts a *single expression* (not statements) generated by an LLM, parses it
through Python's AST, walks it with a whitelist of allowed node types, then
``eval``s it against a namespace containing only ``df`` (and a small set of
numeric/pandas helpers). Guards:

- AST whitelist — anything outside the whitelist raises ``UnsafeCode``.
- ``__builtins__`` zeroed out — no ``open``, ``exec``, ``import``, etc.
- ``signal.SIGALRM`` timeout — 5s default; SIGALRM is POSIX only (Linux/WSL OK).
- Result coerced to a JSON-serializable form for downstream eval.
"""
from __future__ import annotations

import ast
import signal
from dataclasses import dataclass
from typing import Any, Optional

import numpy as np
import pandas as pd


class UnsafeCode(Exception):
    """Raised when the candidate expression contains a disallowed AST node."""


class ExecTimeout(Exception):
    pass


# AST nodes allowed in expressions. Statements, imports, comprehensions with
# generator scope leaks, lambdas, etc. are all rejected.
_ALLOWED_NODES = (
    ast.Expression,
    ast.BinOp, ast.UnaryOp, ast.BoolOp, ast.Compare,
    ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod, ast.Pow,
    ast.UAdd, ast.USub, ast.Not,
    ast.And, ast.Or,
    ast.Eq, ast.NotEq, ast.Lt, ast.LtE, ast.Gt, ast.GtE, ast.In, ast.NotIn,
    ast.Call, ast.Attribute, ast.Subscript, ast.Name, ast.Load,
    ast.Constant,
    ast.Tuple, ast.List, ast.Dict, ast.Set,
    ast.Slice,
    ast.IfExp,
    ast.Index,           # py<3.9 compat; harmless on 3.12
    ast.Starred,
)


def _ast_walk_whitelist(tree: ast.AST) -> None:
    for node in ast.walk(tree):
        if not isinstance(node, _ALLOWED_NODES):
            raise UnsafeCode(f"Disallowed AST node: {type(node).__name__}")
        # Block dunder access like df.__class__.__base__...
        if isinstance(node, ast.Attribute) and node.attr.startswith("__"):
            raise UnsafeCode(f"Disallowed attribute: {node.attr}")


# Names visible inside the evaluated expression.
def _safe_globals(df: pd.DataFrame) -> dict:
    return {
        "__builtins__": {},
        "df": df,
        "pd": pd,
        "np": np,
        "len": len,
        "min": min,
        "max": max,
        "sum": sum,
        "abs": abs,
        "round": round,
        "float": float,
        "int": int,
        "str": str,
        "list": list,
        "tuple": tuple,
        "set": set,
        "sorted": sorted,
        "any": any,
        "all": all,
        "range": range,
        "enumerate": enumerate,
        "zip": zip,
        "True": True, "False": False, "None": None,
    }


@dataclass
class SandboxResult:
    ok: bool
    value: Any = None
    error: Optional[str] = None
    error_type: Optional[str] = None  # "unsafe" | "syntax" | "timeout" | "runtime"


def _alarm_handler(signum, frame):  # noqa: ARG001
    raise ExecTimeout()


def run_sandboxed(code: str, df: pd.DataFrame, timeout_sec: int = 5) -> SandboxResult:
    """Parse, validate, and evaluate ``code`` against ``df``.

    The code must be a single Python expression — not a statement, not a block.
    """
    code = code.strip()
    if not code:
        return SandboxResult(ok=False, error="empty code", error_type="syntax")

    # Strip code-fence wrappers ('```python ... ```') the LLM often adds.
    if code.startswith("```"):
        code = "\n".join(line for line in code.splitlines() if not line.startswith("```"))
        code = code.strip()
    # If the LLM emitted multiple lines (assignments + final expr), take the
    # last non-blank one.
    if "\n" in code:
        non_blank = [ln.strip() for ln in code.splitlines() if ln.strip()]
        if non_blank:
            code = non_blank[-1]

    try:
        tree = ast.parse(code, mode="eval")
    except SyntaxError as e:
        return SandboxResult(ok=False, error=f"SyntaxError: {e}", error_type="syntax")

    try:
        _ast_walk_whitelist(tree)
    except UnsafeCode as e:
        return SandboxResult(ok=False, error=str(e), error_type="unsafe")

    globs = _safe_globals(df)

    prev_handler = signal.signal(signal.SIGALRM, _alarm_handler)
    signal.alarm(timeout_sec)
    try:
        value = eval(compile(tree, "<sandbox>", mode="eval"), globs, {})
    except ExecTimeout:
        return SandboxResult(ok=False, error=f"timeout {timeout_sec}s", error_type="timeout")
    except Exception as e:
        return SandboxResult(ok=False, error=f"{type(e).__name__}: {e}", error_type="runtime")
    finally:
        signal.alarm(0)
        signal.signal(signal.SIGALRM, prev_handler)

    # Normalize result to JSON-safe form.
    value = _normalize(value)
    return SandboxResult(ok=True, value=value)


def _normalize(v):
    """Convert numpy/pandas scalars and small containers to JSON-safe values."""
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return float(v)
    if isinstance(v, (np.bool_,)):
        return bool(v)
    if isinstance(v, pd.Timestamp):
        return v.isoformat()
    if isinstance(v, (pd.Series, pd.Index)):
        return [_normalize(x) for x in v.tolist()]
    if isinstance(v, pd.DataFrame):
        if v.size == 1:
            return _normalize(v.iat[0, 0])
        return v.to_dict(orient="records")
    if isinstance(v, (list, tuple)):
        return [_normalize(x) for x in v]
    if isinstance(v, dict):
        return {str(k): _normalize(val) for k, val in v.items()}
    return v
